name: Ex 2 - Tests

on: [push]
jobs:
  exercise:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🥝 Starting..."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build App
        run: npm run build
